title: COVID-19 em Santos/SP
email: jmsvaz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Acompanhando os casos de COVID-19 em Santos/SP.
github_username:  jmsvaz

locale: pt-BR
theme: jekyll-theme-dinky